import { readFile, writeFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const root = dirname(fileURLToPath(import.meta.url));
const numbers = {
  tamil: [['ஒன்பது','onbadhu','nine'],['பத்து','pathu','ten'],['பதினொன்று','pathinondru','eleven'],['பன்னிரண்டு','pannirandu','twelve'],['பதின்மூன்று','pathinmoondru','thirteen'],['பதினான்கு','pathinaangu','fourteen'],['பதினைந்து','pathinaindhu','fifteen'],['பதினாறு','pathinaaru','sixteen'],['பதினேழு','pathinezhu','seventeen'],['பதினெட்டு','pathinettu','eighteen'],['பத்தொன்பது','paththonbadhu','nineteen'],['இருபது','irubadhu','twenty'],['இருபத்தொன்று','irupaththondru','twenty-one'],['இருபத்திரண்டு','irupaththirandu','twenty-two'],['இருபத்துமூன்று','irupaththimoonru','twenty-three'],['இருபத்திநான்கு','irupaththinaangu','twenty-four']],
  hindi: [['नौ','nau','nine'],['दस','das','ten'],['ग्यारह','gyarah','eleven'],['बारह','barah','twelve'],['तेरह','terah','thirteen'],['चौदह','chaudah','fourteen'],['पंद्रह','pandrah','fifteen'],['सोलह','solah','sixteen'],['सत्रह','satrah','seventeen'],['अठारह','atharah','eighteen'],['उन्नीस','unnees','nineteen'],['बीस','bees','twenty'],['इक्कीस','ikkis','twenty-one'],['बाईस','baais','twenty-two'],['तेईस','teis','twenty-three'],['चौबीस','chaubis','twenty-four']],
  malayalam: [['ഒമ്പത്','ompathu','nine'],['പത്ത്','pathu','ten'],['പതിനൊന്ന്','pathinonnu','eleven'],['പന്ത്രണ്ട്','pantrandu','twelve'],['പതിമൂന്ന്','pathimoonnu','thirteen'],['പതിനാല്','pathinaalu','fourteen'],['പതിനഞ്ച്','pathinanju','fifteen'],['പതിനാറ്','pathinaaru','sixteen'],['പതിനേഴ്','pathinezhu','seventeen'],['പതിനെട്ട്','pathinettu','eighteen'],['പത്തൊമ്പത്','pathonpathu','nineteen'],['ഇരുപത്','irupathu','twenty'],['ഇരുപത്തൊന്ന്','irupathonnu','twenty-one'],['ഇരുപത്തിരണ്ട്','irupathirandu','twenty-two'],['ഇരുപത്തിമൂന്ന്','irupathimoonnu','twenty-three'],['ഇരുപത്തിനാല്','irupathinaalu','twenty-four']],
  spanish: [['nueve','','nine'],['diez','','ten'],['once','','eleven'],['doce','','twelve'],['trece','','thirteen'],['catorce','','fourteen'],['quince','','fifteen'],['dieciséis','','sixteen'],['diecisiete','','seventeen'],['dieciocho','','eighteen'],['diecinueve','','nineteen'],['veinte','','twenty'],['veintiuno','','twenty-one'],['veintidós','','twenty-two'],['veintitrés','','twenty-three'],['veinticuatro','','twenty-four']],
  french: [['neuf','','nine'],['dix','','ten'],['onze','','eleven'],['douze','','twelve'],['treize','','thirteen'],['quatorze','','fourteen'],['quinze','','fifteen'],['seize','','sixteen'],['dix-sept','','seventeen'],['dix-huit','','eighteen'],['dix-neuf','','nineteen'],['vingt','','twenty'],['vingt et un','','twenty-one'],['vingt-deux','','twenty-two'],['vingt-trois','','twenty-three'],['vingt-quatre','','twenty-four']],
};
const greetings = {
  tamil: [['நீங்கள் எப்படி இருக்கிறீர்கள்?','neengal eppadi irukkireergal?','how are you?'],['நான் நலமாக இருக்கிறேன்','naan nalamaaga irukkiren','I am well'],['உங்கள் பெயர் என்ன?','ungal peyar enna?','what is your name?'],['என் பெயர் ...','en peyar ...','my name is'],['உங்களை சந்தித்ததில் மகிழ்ச்சி','ungalai sandhithathil magizhchi','nice to meet you'],['நீங்கள் எங்கிருந்து வருகிறீர்கள்?','neengal engirundhu varugireergal?','where are you from?'],['மாலை வணக்கம்','maalai vanakkam','good evening'],['வரவேற்கிறேன்','varaverkiren','welcome'],['மீண்டும் சந்திப்போம்','meendum sandhippom','see you again'],['தயவுசெய்து உதவுங்கள்','thayavuseithu udhavungal','please help me'],['மெதுவாகப் பேசுங்கள்','medhuvaaga pesungal','speak slowly'],['எனக்குப் புரியவில்லை','enakku puriyavillai','I do not understand'],['ஆங்கிலம் பேசுவீர்களா?','aangilam pesuveergalaa?','do you speak English?'],['எனக்குக் கொஞ்சம் தெரியும்','enakku konjam theriyum','I know a little'],['நாளை சந்திப்போம்','naalai sandhippom','see you tomorrow'],['நல்ல நாளாக இருக்கட்டும்','nalla naalaaga irukkattum','have a nice day']],
  hindi: [['आप कैसे हैं?','aap kaise hain?','how are you?'],['मैं ठीक हूँ','main theek hoon','I am well'],['आपका नाम क्या है?','aapka naam kya hai?','what is your name?'],['मेरा नाम ... है','mera naam ... hai','my name is'],['आपसे मिलकर खुशी हुई','aapse milkar khushi hui','nice to meet you'],['आप कहाँ से हैं?','aap kahaan se hain?','where are you from?'],['शुभ संध्या','shubh sandhya','good evening'],['आपका स्वागत है','aapka swagat hai','welcome'],['फिर मिलेंगे','phir milenge','see you again'],['कृपया मेरी मदद कीजिए','kripya meri madad kijiye','please help me'],['कृपया धीरे बोलिए','kripya dheere boliye','speak slowly'],['मुझे समझ नहीं आया','mujhe samajh nahin aaya','I do not understand'],['क्या आप अंग्रेज़ी बोलते हैं?','kya aap angrezi bolte hain?','do you speak English?'],['मुझे थोड़ी हिंदी आती है','mujhe thodi hindi aati hai','I know a little'],['कल मिलते हैं','kal milte hain','see you tomorrow'],['आपका दिन अच्छा हो','aapka din achchha ho','have a nice day']],
  malayalam: [['സുഖമാണോ?','sukhamaano?','how are you?'],['എനിക്ക് സുഖമാണ്','enikku sukhamaanu','I am well'],['നിങ്ങളുടെ പേര് എന്താണ്?','ningalude peru enthaanu?','what is your name?'],['എന്റെ പേര് ...','ente peru ...','my name is'],['കണ്ടതിൽ സന്തോഷം','kandathil santhosham','nice to meet you'],['നിങ്ങൾ എവിടെ നിന്നാണ്?','ningal evide ninnaanu?','where are you from?'],['ശുഭ സായാഹ്നം','shubha saayaahnam','good evening'],['സ്വാഗതം','swaagatham','welcome'],['വീണ്ടും കാണാം','veendum kaanaam','see you again'],['ദയവായി എന്നെ സഹായിക്കൂ','dayavaayi enne sahaayikku','please help me'],['ദയവായി പതുക്കെ സംസാരിക്കൂ','dayavaayi pathukke samsaarikku','speak slowly'],['എനിക്ക് മനസ്സിലായില്ല','enikku manassilaayilla','I do not understand'],['നിങ്ങൾ ഇംഗ്ലീഷ് സംസാരിക്കുമോ?','ningal english samsaarikkumo?','do you speak English?'],['എനിക്ക് കുറച്ച് അറിയാം','enikku kurachu ariyaam','I know a little'],['നാളെ കാണാം','naale kaanaam','see you tomorrow'],['നല്ലൊരു ദിവസം ആശംസിക്കുന്നു','nalloru divasam aashamsikkunnu','have a nice day']],
  spanish: [['¿Cómo estás?','','how are you?'],['Estoy bien','','I am well'],['¿Cómo te llamas?','','what is your name?'],['Me llamo ...','','my name is'],['Mucho gusto','','nice to meet you'],['¿De dónde eres?','','where are you from?'],['Buenas tardes','','good evening'],['Bienvenido','','welcome'],['Hasta luego','','see you again'],['Ayúdame, por favor','','please help me'],['Habla despacio, por favor','','speak slowly'],['No entiendo','','I do not understand'],['¿Hablas inglés?','','do you speak English?'],['Hablo un poco','','I know a little'],['Hasta mañana','','see you tomorrow'],['Que tengas un buen día','','have a nice day']],
  french: [['Comment allez-vous ?','','how are you?'],['Je vais bien','','I am well'],['Comment vous appelez-vous ?','','what is your name?'],["Je m’appelle ...",'','my name is'],['Enchanté(e)','','nice to meet you'],['Vous venez d’où ?','','where are you from?'],['Bonsoir','','good evening'],['Bienvenue','','welcome'],['À bientôt','','see you again'],['Aidez-moi, s’il vous plaît','','please help me'],['Parlez lentement, s’il vous plaît','','speak slowly'],['Je ne comprends pas','','I do not understand'],['Parlez-vous anglais ?','','do you speak English?'],['Je parle un peu','','I know a little'],['À demain','','see you tomorrow'],['Bonne journée','','have a nice day']],
};
const food = {
  tamil: [['பழம்','palam','fruit'],['வாழைப்பழம்','vaazhaipazham','banana'],['மாம்பழம்','maampazham','mango'],['தக்காளி','thakkaali','tomato'],['உருளைக்கிழங்கு','urulaikkizhangu','potato'],['முட்டை','muttai','egg'],['கோழி','kozhi','chicken'],['மீன்','meen','fish'],['உப்பு','uppu','salt'],['சர்க்கரை','sarkkarai','sugar'],['மிளகு','milagu','pepper'],['காய்கறி','kaaykari','vegetable'],['பழச்சாறு','pazhachaaru','fruit juice'],['தயிர்','thayir','yogurt'],['இட்லி','idli','idli'],['தோசை','dosai','dosa']],
  hindi: [['फल','phal','fruit'],['केला','kela','banana'],['आम','aam','mango'],['टमाटर','tamatar','tomato'],['आलू','aaloo','potato'],['अंडा','anda','egg'],['चिकन','chicken','chicken'],['मछली','machhli','fish'],['नमक','namak','salt'],['चीनी','cheeni','sugar'],['काली मिर्च','kaali mirch','pepper'],['सब्ज़ी','sabzi','vegetable'],['फलों का रस','phalon ka ras','fruit juice'],['दही','dahi','yogurt'],['इडली','idli','idli'],['डोसा','dosa','dosa']],
  malayalam: [['പഴം','pazham','fruit'],['വാഴപ്പഴം','vaazhappazham','banana'],['മാമ്പഴം','maampazham','mango'],['തക്കാളി','thakkaali','tomato'],['ഉരുളക്കിഴങ്ങ്','urulakkizhangu','potato'],['മുട്ട','mutta','egg'],['കോഴി','kozhi','chicken'],['മീൻ','meen','fish'],['ഉപ്പ്','uppu','salt'],['പഞ്ചസാര','panchasaara','sugar'],['കുരുമുളക്','kurumulaku','pepper'],['പച്ചക്കറി','pachakkari','vegetable'],['പഴച്ചാർ','pazhachaaru','fruit juice'],['തൈര്','thairu','yogurt'],['ഇഡലി','idali','idli'],['ദോശ','dosha','dosa']],
  spanish: [['fruta','','fruit'],['plátano','','banana'],['mango','','mango'],['tomate','','tomato'],['patata','','potato'],['huevo','','egg'],['pollo','','chicken'],['pescado','','fish'],['sal','','salt'],['azúcar','','sugar'],['pimienta','','pepper'],['verdura','','vegetable'],['zumo de fruta','','fruit juice'],['yogur','','yogurt'],['tortilla','','omelette'],['galleta','','biscuit']],
  french: [['fruit','','fruit'],['banane','','banana'],['mangue','','mango'],['tomate','','tomato'],['pomme de terre','','potato'],['œuf','','egg'],['poulet','','chicken'],['poisson','','fish'],['sel','','salt'],['sucre','','sugar'],['poivre','','pepper'],['légume','','vegetable'],['jus de fruits','','fruit juice'],['yaourt','','yogurt'],['omelette','','omelette'],['biscuit','','biscuit']],
};

for (const lang of Object.keys(numbers)) {
  const path = join(root, `${lang}.json`);
  const data = JSON.parse(await readFile(path, 'utf8'));
  [numbers[lang], greetings[lang], food[lang]].forEach((items, index) => {
    if (data.units[index].words.length === 8) data.units[index].words.push(...items);
    if (data.units[index].words.length !== 24) throw new Error(`${lang} ${data.units[index].title} must contain 8 or 24 entries before expansion.`);
  });
  await writeFile(path, `${JSON.stringify(data, null, 2)}\n`, 'utf8');
}
console.log('Expanded all five courses to 24 items per unit.');
