import 'dotenv/config'; import express from 'express'; import cors from 'cors'; import cookieParser from 'cookie-parser'; import rateLimit from 'express-rate-limit'; import jwt from 'jsonwebtoken'; import bcrypt from 'bcryptjs'; import {z} from 'zod'; import {PrismaClient} from '@prisma/client'; import {isCorrect,nextStreak} from './logic.js'; import {sendVerificationCode} from './email.js'; import {createHmac,randomInt,timingSafeEqual} from 'node:crypto';
import {resolve} from 'node:path';
const app=express(),db=new PrismaClient(),secret=process.env.JWT_SECRET||'dev-only-secret'; app.use(cors({origin:process.env.CLIENT_URL||'http://localhost:5173',credentials:true}));app.use(express.json());app.use(cookieParser());
if(process.env.VERCEL==='1'&&!process.env.JWT_SECRET)throw new Error('JWT_SECRET must be configured in Vercel before deployment.');
// Vercel routes API requests through this single Express function and passes the original path as `route`.
app.use((req:any,_res,next)=>{if(process.env.VERCEL&&typeof req.query.route==='string'&&req.query.route.startsWith('/api/'))req.url=req.query.route;next()});
const authLimit=rateLimit({windowMs:15*60*1000,max:30}); const auth=(req:any,res:any,next:any)=>{try{req.user=jwt.verify(req.cookies.token,secret);next()}catch{return res.status(401).json({error:'Please sign in'})}};
app.get('/api/health',(_,r)=>r.json({ok:true}));
function codeDigest(email:string,purpose:string,code:string){return createHmac('sha256',secret).update(`${email}:${purpose}:${code}`).digest('hex')}
async function issueCode(email:string,purpose:string){const code=String(randomInt(100000,1000000));await db.emailOtp.deleteMany({where:{email,purpose}});await db.emailOtp.create({data:{email,purpose,codeHash:codeDigest(email,purpose,code),expiresAt:new Date(Date.now()+10*60*1000)}});await sendVerificationCode(email,code)}
app.post('/api/auth/signup',authLimit,async(req,res)=>{const p=z.object({email:z.string().email(),name:z.string().trim().min(1).max(80),password:z.string().min(8).max(72)}).safeParse(req.body);if(!p.success)return res.status(400).json({error:'Enter your name, a valid email, and a password with at least 8 characters.'});const email=p.data.email.toLowerCase();let user=await db.user.findUnique({where:{email}});if(user?.emailVerified)return res.status(409).json({error:'This email already has an account. Log in instead.'});const passwordHash=await bcrypt.hash(p.data.password,12);if(!user)user=await db.user.create({data:{email,name:p.data.name,passwordHash}});else user=await db.user.update({where:{id:user.id},data:{name:p.data.name,passwordHash}});try{await issueCode(email,'signup')}catch(e){console.error(e);return res.status(503).json({error:'Could not send your verification code. Check the email sender settings.'})}res.json({requiresOtp:true,email,purpose:'signup',message:`We sent a 6-digit code to ${email}.`})});
app.post('/api/auth/login',authLimit,async(req,res)=>{const p=z.object({email:z.string().email(),password:z.string().min(1).max(72)}).safeParse(req.body);if(!p.success)return res.status(400).json({error:'Enter a valid email and password.'});const email=p.data.email.toLowerCase();const user=await db.user.findUnique({where:{email}});if(!user)return res.status(401).json({error:'Email or password is incorrect.'});if(!user.emailVerified)return res.status(403).json({error:'Please verify your email using the code sent during registration.'});if(!user.passwordHash){try{await issueCode(email,'login')}catch(e){console.error(e);return res.status(503).json({error:'Could not send your verification code. Check the email sender settings.'})}return res.json({requiresOtp:true,email,purpose:'login',message:`We sent a one-time code to ${email}. Enter it once to set your password.`})}if(!await bcrypt.compare(p.data.password,user.passwordHash))return res.status(401).json({error:'Email or password is incorrect.'});res.cookie('token',jwt.sign({id:user.id},secret,{expiresIn:'7d'}),{httpOnly:true,sameSite:'lax',secure:process.env.NODE_ENV==='production',maxAge:7*864e5});res.json({id:user.id,name:user.name,email:user.email})});
app.post('/api/auth/resend-code',authLimit,async(req,res)=>{const p=z.object({email:z.string().email(),purpose:z.enum(['signup','login'])}).safeParse(req.body);if(!p.success)return res.status(400).json({error:'Invalid request'});const email=p.data.email.toLowerCase();const user=await db.user.findUnique({where:{email}});if(!user||((p.data.purpose==='login')!==user.emailVerified))return res.json({ok:true,message:'If the account can receive a code, a new code has been sent.'});const previous=await db.emailOtp.findFirst({where:{email,purpose:p.data.purpose},orderBy:{createdAt:'desc'}});if(previous&&Date.now()-previous.createdAt.getTime()<60_000)return res.status(429).json({error:'Please wait a minute before requesting another code.'});try{await issueCode(email,p.data.purpose);res.json({ok:true,message:`A new code was sent to ${email}.`})}catch(e){console.error(e);res.status(503).json({error:'Email code could not be sent. Please try again later.'})}});
app.post('/api/auth/verify-otp',authLimit,async(req,res)=>{const p=z.object({email:z.string().email(),code:z.string().regex(/^\d{6}$/),purpose:z.enum(['signup','login']),newPassword:z.string().min(8).max(72).optional()}).safeParse(req.body);if(!p.success)return res.status(400).json({error:'Enter the 6-digit code from your email.'});const email=p.data.email.toLowerCase();const challenge=await db.emailOtp.findFirst({where:{email,purpose:p.data.purpose},orderBy:{createdAt:'desc'}});if(!challenge||challenge.expiresAt.getTime()<Date.now()||challenge.attempts>=5)return res.status(400).json({error:'That code has expired. Request a new one.'});const actual=Buffer.from(codeDigest(email,p.data.purpose,p.data.code));const expected=Buffer.from(challenge.codeHash);const valid=actual.length===expected.length&&timingSafeEqual(actual,expected);if(!valid){const attempts=challenge.attempts+1;await db.emailOtp.update({where:{id:challenge.id},data:{attempts}});return res.status(400).json({error:attempts>=5?'Too many attempts. Request a new code.':'That code is incorrect. Try again.'})}let user=await db.user.findUnique({where:{email}});if(!user)return res.status(400).json({error:'Account not found. Please sign up again.'});if(p.data.purpose==='login'&&!user.emailVerified)return res.status(403).json({error:'Verify your email address before logging in.'});if(p.data.purpose==='login'&&!user.passwordHash){if(!p.data.newPassword)return res.status(400).json({error:'Create a password with at least 8 characters to finish signing in.'});user=await db.user.update({where:{id:user.id},data:{passwordHash:await bcrypt.hash(p.data.newPassword,12)}})}await db.emailOtp.deleteMany({where:{email}});if(p.data.purpose==='signup')user=await db.user.update({where:{id:user.id},data:{emailVerified:true}});res.cookie('token',jwt.sign({id:user.id},secret,{expiresIn:'7d'}),{httpOnly:true,sameSite:'lax',secure:process.env.NODE_ENV==='production',maxAge:7*864e5});res.json({id:user.id,name:user.name,email:user.email})});
app.post('/api/auth/logout',(_,res)=>{res.clearCookie('token');res.json({ok:true})});app.get('/api/auth/me',auth,async(req:any,res)=>{const u=await db.user.findUnique({where:{id:req.user.id},select:{id:true,email:true,name:true}});res.json(u)});
app.get('/api/courses',auth,async(req:any,res)=>{const courses=await db.course.findMany({include:{units:{orderBy:{order:'asc'},include:{lessons:{orderBy:{order:'asc'},include:{_count:{select:{exercises:true}}}}}},enrollments:req.user?{where:{userId:req.user.id}}:false}});res.json(courses)});
app.post('/api/courses/:id/enroll',auth,async(req:any,res)=>{try{res.json(await db.enrollment.upsert({where:{userId_courseId:{userId:req.user.id,courseId:req.params.id}},create:{userId:req.user.id,courseId:req.params.id},update:{}}))}catch{return res.status(404).json({error:'Course not found'})}});
app.get('/api/progress',auth,async(req:any,res)=>res.json(await db.lessonProgress.findMany({where:{userId:req.user.id},include:{lesson:true}})));
app.get('/api/profile',auth,async(req:any,res)=>{const u=await db.user.findUnique({where:{id:req.user.id},include:{badges:{include:{badge:true}},enrollments:{include:{course:true}},progress:{where:{completed:true}}}});res.json(u)});
app.get('/api/leaderboard',async(_,res)=>{const since=new Date();since.setDate(since.getDate()-7);const list=await db.user.findMany({select:{name:true,progress:{where:{completedAt:{gte:since}},select:{xpEarned:true}}}});res.json(list.map(u=>({name:u.name,xp:u.progress.reduce((a,p)=>a+p.xpEarned,0)})).sort((a,b)=>b.xp-a.xp).slice(0,10))});
app.get('/api/lessons/:id',auth,async(req:any,res)=>{const l=await db.lesson.findUnique({where:{id:req.params.id},include:{unit:{include:{course:true}},exercises:{orderBy:{order:'asc'}}}});if(!l)return res.status(404).json({error:'Lesson not found'});const enrolled=await db.enrollment.findUnique({where:{userId_courseId:{userId:req.user.id,courseId:l.unit.courseId}}});if(!enrolled)return res.status(403).json({error:'Enroll in this course first'});const all=await db.lesson.findMany({where:{unit:{courseId:l.unit.courseId}},orderBy:[{unit:{order:'asc'}},{order:'asc'}]});const idx=all.findIndex(x=>x.id===l.id);if(idx>0){const prev=await db.lessonProgress.findUnique({where:{userId_lessonId:{userId:req.user.id,lessonId:all[idx-1].id}}});if(!prev?.completed)return res.status(403).json({error:'Complete the previous lesson to unlock this one'})}res.json({...l,exercises:l.exercises.map(e=>({...e,options:JSON.parse(e.options)}))})});
app.post('/api/lessons/:id/submit',auth,async(req:any,res)=>{const p=z.object({answers:z.array(z.object({exerciseId:z.string(),answer:z.string()}))}).safeParse(req.body);if(!p.success)return res.status(400).json({error:'Invalid answers'});const l=await db.lesson.findUnique({where:{id:req.params.id},include:{exercises:true,unit:{include:{course:true}}}});if(!l)return res.status(404).json({error:'Lesson not found'});const u=await db.user.findUniqueOrThrow({where:{id:req.user.id}});let right=0;for(const e of l.exercises){const answer=p.data.answers.find(a=>a.exerciseId===e.id)?.answer||'';if(isCorrect(e.answer,answer))right++;else await db.mistakeLog.create({data:{userId:u.id,exerciseId:e.id}})}const accuracy=l.exercises.length?right/l.exercises.length:0,xp=right*10;await db.lessonProgress.upsert({where:{userId_lessonId:{userId:u.id,lessonId:l.id}},create:{userId:u.id,lessonId:l.id,completed:true,accuracy,xpEarned:xp,completedAt:new Date()},update:{completed:true,accuracy,xpEarned:xp,completedAt:new Date()}});await db.user.update({where:{id:u.id},data:{xp:{increment:xp},streak:nextStreak(u.streak,u.lastActive),lastActive:new Date()}});const unlocks=[['first','First Lesson','Complete your first lesson'],['xp100','100 XP','Earn 100 XP'],['perfect','Perfect Lesson','Get every answer correct']];const criteria=[true,u.xp+xp>=100,accuracy===1];for(let i=0;i<unlocks.length;i++)if(criteria[i]){const [code,name,description]=unlocks[i];await db.badge.upsert({where:{code},create:{code,name,description},update:{}});const b=await db.badge.findUniqueOrThrow({where:{code}});await db.userBadge.upsert({where:{userId_badgeId:{userId:u.id,badgeId:b.id}},create:{userId:u.id,badgeId:b.id},update:{}})}res.json({accuracy,xp,correct:right,total:l.exercises.length})});
app.get('/api/practice',auth,async(req:any,res)=>{const misses=await db.mistakeLog.findMany({where:{userId:(req as any).user.id},distinct:['exerciseId'],include:{user:true}});const exercises=await db.exercise.findMany({where:{id:{in:misses.map(m=>m.exerciseId)}},include:{lesson:{include:{unit:{include:{course:true}}}}}});res.json(exercises.map(e=>({...e,options:JSON.parse(e.options)})))});
app.post('/api/practice/:id',auth,async(req:any,res)=>{const e=await db.exercise.findUnique({where:{id:req.params.id}});if(!e)return res.status(404).json({error:'Exercise not found'});const ok=isCorrect(e.answer,String(req.body.answer||''));if(ok)await db.mistakeLog.deleteMany({where:{userId:req.user.id,exerciseId:e.id}});res.json({correct:ok,answer:e.answer})});
if(process.env.VERCEL!=='1'){const clientBuild=resolve(process.cwd(),'../public');app.use(express.static(clientBuild));app.get('*',(req,res,next)=>{if(req.path.startsWith('/api/'))return next();res.sendFile(resolve(clientBuild,'index.html'))})}
app.use((err:any,_req:any,res:any,_next:any)=>{console.error(err);res.status(500).json({error:'Something went wrong'})});
export default app;
if(process.env.VERCEL!=='1')app.listen(Number(process.env.PORT)||4000,'0.0.0.0',()=>console.log(`LinguaLeap API listening on ${Number(process.env.PORT)||4000}`));

